apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: bookstore-webapp-pipeline
  spec:
    description: A java springboot ReST service pipeline
    params:
    - default: {{ .Release.Namespace }}
      description: The target namespace
      name: target-namespace
      type: string
    - default: bookstore-webapp
      description: The application name
      name: application-name
      type: string         
    tasks:
    - name: fetch-repository
      params:
      - name: url
        value: {{ .Values.pipelines.giturl }}
      - name: deleteExisting
        value: "true"
      - name: subdirectory
        value: "catalog"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: workspace-acme
    - name: build-app
      runAfter:
      - fetch-repository
      taskRef:
        name: maven-build
      workspaces:
      - name: source
        workspace: workspace-acme
    - name: create-app-image
      params:
      - name: namespace
        value: $(params.target-namespace)
      - name: buildconfig-name
        value: bookstore-webapp
      - name: jar-file-path
        value: /workspace/source/catalog/dev/monolith/bookstore-legacy/target/ROOT.war
      runAfter:
      - build-app
      taskRef:
        name: java-binary-deploy
      workspaces:
      - name: source
        workspace: workspace-acme
    - name: rollout-app
      params:
      - name: namespace
        value: $(params.target-namespace)
      - name: deployment-name
        value: $(params.application-name)          
      runAfter:
      - create-app-image
      taskRef:
        name: deployment-rollout
      workspaces:
      - name: source
        workspace: workspace-acme        
    workspaces:
    - name: workspace-acme
kind: List
metadata: {}