apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: bookstore-webapp
    app.kubernetes.io/component: bookstore-webapp
    app.kubernetes.io/instance: bookstore-webapp
  name: bookstore-webapp
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: bookstore-webapp
    weight: 100
  wildcardPolicy: None