apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: bookstore-inventory
    app.kubernetes.io/component: bookstore-inventory
    app.kubernetes.io/instance: bookstore-inventory
  name: bookstore-inventory
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: bookstore-inventory:{{ .Values.microservices.config.bookstore.inventory.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.microservices.config.bookstore.inventory.baseimage }}
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5