apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: Task
  metadata:
    name: dotnet-binary-deploy
  spec:
    params:
    - name: namespace
      type: string
    steps:
    - args:
      - oc start-build bookstore-inventory --from-file=/workspace/source/dev/microservices/bookstore-inventory/src/RestAPP/bin/Release/netcoreapp3.1/rhel.7-x64/publish
        -n $(params.namespace) --wait
      command:
      - /bin/bash
      - -c
      image: quay.io/openshift/origin-cli:latest
      name: deploy
    workspaces:
    - description: The workspace where the source code will found
      name: source
kind: List
metadata: {}