apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: 
  name: setup-catalog
spec:
  params:
    - name: target-namespace
      value: innovation-workshop
    - name: application-name
      value: bookstore-catalog
  pipelineRef:
    name: catalog-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace-acme
      persistentVolumeClaim:
        claimName: catalog-pipeline-pvc