apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: 
  name: setup-ui
spec:
  params:
    - name: target-namespace
      value: innovation-workshop
    - name: application-name
      value: bookstore-ui
  pipelineRef:
    name: ui-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace-acme
      persistentVolumeClaim:
        claimName: ui-pipeline-pvc