apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      initContainers:
        - name: check-db-ready
          image: {{ .Values.db.image }}
          command: ['sh', '-c', 
            'until pg_isready -h {{ .Values.db.servicename }} -p 5432; 
            do echo waiting for database; sleep 2; done;']     
      containers:              
        - name: dbsetup
          image: {{ .Values.db.image }}
          command: ['sh', '-c', 
            'psql -h {{ .Values.db.servicename }} -U postgres -d {{ .Values.db.database }} < /opt/app-root/src/data.sql']
          env:
            - name: PGPASSWORD
              value: {{ .Values.db.password }}            
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app-root/src
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.db.servicename }}-init-script
            items:
            - key: data.sql
              path: data.sql            
      restartPolicy: Never
