apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: bookstore-catalog
    app.kubernetes.io/component: bookstore-catalog
    app.kubernetes.io/instance: bookstore-catalog
  name: bookstore-catalog
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: bookstore-catalog
    weight: 100
  wildcardPolicy: None