apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: Pipeline
  metadata:
    name: books-api-pipeline
  spec:
    params:
    - default: {{ .Release.Namespace }}
      description: The target namespace
      name: target-namespace
      type: string
    tasks:
    - name: fetch-repository
      params:
      - name: url
        value: https://github.com/eljeko/tekton-demo
      - name: deleteExisting
        value: "true"
      - name: subdirectory
        value: ""
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: workspace-acme
    - name: build-app
      runAfter:
      - fetch-repository
      taskRef:
        name: maven-build
      workspaces:
      - name: source
        workspace: workspace-acme
    - name: create-app-image
      params:
      - name: namespace
        value: $(params.target-namespace)
      runAfter:
      - build-app
      taskRef:
        name: java-binary-deploy
      workspaces:
      - name: source
        workspace: workspace-acme
    - name: rollout-app
      params:
      - name: namespace
        value: $(params.target-namespace)
      runAfter:
      - create-app-image
      taskRef:
        name: java-rollout
      workspaces:
      - name: source
        workspace: workspace-acme        
    workspaces:
    - name: workspace-acme
kind: List
metadata: {}
