spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: user1
    password: password1
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQL81Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect