apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: bookstore-ui
    app.kubernetes.io/component: bookstore-ui
    app.kubernetes.io/instance: bookstore-ui
  name: bookstore-ui
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: bookstore-ui
    weight: 100
  wildcardPolicy: None