
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: bookstore-ui
    app.kubernetes.io/component: bookstore-ui
    app.kubernetes.io/instance: bookstore-ui
  name: bookstore-ui
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: bookstore-ui:{{ .Values.microservices.config.bookstore.ui.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.microservices.config.bookstore.ui.baseimage }}
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5